name: 'Build Nightly'

on:
  schedule:
    # Run every day at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  build-nightly:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'windows-latest'
            args: ''
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin'

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'x86_64-apple-darwin' || '' }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libssl-dev pkg-config

      - name: install frontend dependencies
        run: npm ci

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ${{ matrix.args }}
          includeDebug: false
          includeRelease: true
          includeUpdaterJson: false

      - name: Debug - List built assets (Unix)
        if: runner.os != 'Windows'
        run: |
          echo "=== Listing src-tauri/target/release/bundle ==="
          find src-tauri/target/release/bundle -type f 2>/dev/null || echo "Bundle directory not found"
          echo "=== Listing target directory structure ==="
          find src-tauri/target -name "*.deb" -o -name "*.rpm" -o -name "*.appimage" -o -name "*.dmg" -o -name "*.app" -o -name "*.msi" -o -name "*.exe" 2>/dev/null || echo "No installer files found"

      - name: Debug - List built assets (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          Write-Host "=== Listing src-tauri/target/release/bundle ==="
          if (Test-Path "src-tauri/target/release/bundle") {
            Get-ChildItem -Path "src-tauri/target/release/bundle" -Recurse -File | Select-Object FullName
          } else {
            Write-Host "Bundle directory not found"
          }
          Write-Host "=== Listing target directory structure ==="
          $files = Get-ChildItem -Path "src-tauri/target" -Recurse -File | Where-Object { $_.Extension -in @('.deb', '.rpm', '.appimage', '.dmg', '.app', '.msi', '.exe') }
          if ($files) {
            $files | Select-Object FullName
          } else {
            Write-Host "No installer files found"
          }

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nightly-${{ matrix.platform }}
          path: |
            src-tauri/target/release/bundle/
          retention-days: 7
