name: 'Test Build'

on:
  workflow_dispatch:

jobs:
  test-build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'ubuntu-22.04'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libssl-dev pkg-config

      - name: install frontend dependencies
        run: npm ci

      - name: lint frontend
        run: npm run lint --if-present

      - name: check Rust formatting
        run: cd src-tauri && cargo fmt --all -- --check

      - name: check Rust code with clippy
        run: cd src-tauri && cargo clippy --all-targets --all-features -- -D warnings

      - name: run Rust tests
        run: cd src-tauri && cargo test

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ${{ matrix.args }}
          includeDebug: false
          includeRelease: true
          includeUpdaterJson: false

      - name: Debug - List built assets
        run: |
          echo "=== Listing src-tauri/target/release/bundle ==="
          find src-tauri/target/release/bundle -type f 2>/dev/null || echo "Bundle directory not found"
          echo "=== Listing target directory structure ==="
          find src-tauri/target -name "*.deb" -o -name "*.rpm" -o -name "*.appimage" -o -name "*.dmg" -o -name "*.app" -o -name "*.msi" -o -name "*.exe" 2>/dev/null || echo "No installer files found"

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-build-${{ matrix.platform }}
          path: |
            src-tauri/target/release/bundle/
          retention-days: 1
